In [ ]:
import pandas as pd

In [ ]:
file_path = 'From_12_1_to_12_31_30_days_total_SD_hotels_list.csv'

In [ ]:
df = pd.read_csv(file_path)

In [ ]:
df

,hotel,hotel_location,price
0,Beauty of Point Loma on the Harbor,"Point Loma, San Diego","$3,953"
1,San Diego Marriott Del Mar,"Carmel Valley, San Diego","$5,370"
2,Artfully-styled bungalow in the heart of it all,San Diego,"$5,120"
3,Fairfield Inn & Suites San Diego Old Town,"Old Town, San Diego","$5,531"
4,OB Holiday,"Ocean Beach, San Diego","$8,919"
...,...,...,...
246,Studio with Large Balcony- San Diego Gateway,"Downtown San Diego, San Diego","$9,777"
247,Legacy Resort Hotel & Spa,"Mission Valley, San Diego","$12,931"
248,Grande Colonial La Jolla,"La Jolla, San Diego","$11,930"
249,The Pearl Hotel,"Point Loma, San Diego","$7,920"
250,The Inn at Sunset Cliffs,"Point Loma, San Diego","$9,190"

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df

,hotel,hotel_location,price
0,Beauty of Point Loma on the Harbor,"Point Loma, San Diego","$3,953"
1,San Diego Marriott Del Mar,"Carmel Valley, San Diego","$5,370"
2,Artfully-styled bungalow in the heart of it all,San Diego,"$5,120"
3,Fairfield Inn & Suites San Diego Old Town,"Old Town, San Diego","$5,531"
4,OB Holiday,"Ocean Beach, San Diego","$8,919"
...,...,...,...
246,Studio with Large Balcony- San Diego Gateway,"Downtown San Diego, San Diego","$9,777"
247,Legacy Resort Hotel & Spa,"Mission Valley, San Diego","$12,931"
248,Grande Colonial La Jolla,"La Jolla, San Diego","$11,930"
249,The Pearl Hotel,"Point Loma, San Diego","$7,920"
250,The Inn at Sunset Cliffs,"Point Loma, San Diego","$9,190"

In [ ]:
df.reset_index(drop=True)

,hotel,hotel_location,price
0,Beauty of Point Loma on the Harbor,"Point Loma, San Diego","$3,953"
1,San Diego Marriott Del Mar,"Carmel Valley, San Diego","$5,370"
2,Artfully-styled bungalow in the heart of it all,San Diego,"$5,120"
3,Fairfield Inn & Suites San Diego Old Town,"Old Town, San Diego","$5,531"
4,OB Holiday,"Ocean Beach, San Diego","$8,919"
...,...,...,...
217,Studio with Large Balcony- San Diego Gateway,"Downtown San Diego, San Diego","$9,777"
218,Legacy Resort Hotel & Spa,"Mission Valley, San Diego","$12,931"
219,Grande Colonial La Jolla,"La Jolla, San Diego","$11,930"
220,The Pearl Hotel,"Point Loma, San Diego","$7,920"
221,The Inn at Sunset Cliffs,"Point Loma, San Diego","$9,190"

In [ ]:
output_file_path = '30night_remove_duplicate.csv'  # Replace with your desired output file path
df.to_csv(output_file_path, index=False)

print(f"Deduplicated file saved to {output_file_path}")

Deduplicated file saved to 30night_remove_duplicate.csv